### ISSUE TITLE
Trying to get property 'urlCacheSessionKey' of non-object

### ISSUE THREAD

**Issue by arunwebber** [ogheo/yii2-comments#6]
I am getting this error I have configured comment widget in this way.
```
<?=  Comments::widget();
    ?>
```
Everything worked the widget is showing the comment section to logged in users also user is able to post comment the comments are getting stored in Db as well but after posting the comment this error is showing to the user.

**Comment by ogheo** [comment]
can you provide more info? on my side with Yii 2 Advanced Project Template seems to work as expected.

**Comment by arunwebber** [comment]
> can you provide more info? on my side, with Yii 2 Advanced Project Template seems to work as expected.

I have updated the issue description

**Comment by arunwebber** [comment]
I have stopped using the widget any way as you have replied i pulled the latest code but this time  I a getting a diffrent error Which is this
https://github.com/ogheo/yii2-comments/issues/7

**Comment by ogheo** [comment]
To be able to reproduce I would like to know which yii2 template you're using? (basic/advanced), php / mysql version? Otherwise I can't help You.

**Comment by arunwebber** [comment]
> To be able to reproduce I would like to know which yii2 template you're using? (basic/advanced), php / mysql version? Otherwise I can't help You.

I am using yii2 advanced template 2.0.16-dev 
Mysql: MySQL  Ver 14.14 Distrib 5.5.55
php:PHP Version 7.2.3-1+ubuntu14.04.1+deb.sury.org+1

**Comment by ogheo** [comment]
Well, on my side everything work as expected... try to check if module is connected in main.php config file.
I suppose you missed this step.

**Comment by arunwebber** [comment]
I couldn't retest them can you see the latest comment on this issue https://github.com/ogheo/yii2-comments/issues/7
