### ISSUE TITLE
add foreign key comments_rating_fidkey: {{%comments_rating}} (comment_id) references {{%comments}} (id) ...Exception: SQLSTATE[HY000]: General error: 1005 Can't create table 'db.#sql-51c_d6' (errno: 150)

### ISSUE THREAD

**Issue by arunwebber** [ogheo/yii2-comments#7]
I am getting this error while applying migration also I have found that the comments table is not got created in DB whereas as the table comments_rating is got created.

**Comment by ogheo** [comment]
Error is due missing comments table. Why this happens? not sure but check db to be innodb, check migration table and so on... issue is on your side, nothing to do here.

**Comment by arunwebber** [comment]
> Error is due missing comments table. Why this happens? not sure but check db to be innodb, check migration table and so on... issue is on your side, nothing to do here.

Can you give me direct query of these tables without migrations so that i can create those tables from my end
