### ISSUE TITLE
How to set action urls?

### ISSUE THREAD

**Issue by kwazaro** [ogheo/yii2-comments#8]
How to set correct routes to comment create, thumbs-up and thumbs-down actions, because default values are related to page, where widget is called?

**Comment by ogheo** [comment]
You can see all default routes here: https://github.com/ogheo/yii2-comments/blob/master/src/Bootstrap.php

to access them you have to call for example: comments/default/create.

You can also overwrite them in main.php config file.

**Comment by kwazaro** [comment]
Thanks!
